# Generated by Django 5.0 on 2024-01-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_learningModules', '0003_remove_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
