# Generated by Django 5.0 on 2024-01-20 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_learningModules', '0005_alter_course_options_course_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order']},
        ),
    ]
